# |------------------------------------------------------------------------
# |              Archivo De Configuraciones de Events Switch
# |                               By Goottsy
# |                      https://twitter.com/Goottsy
# |------------------------------------------------------------------------

hunger: true
pvp: true